#imagen a usar
FROM python:3.10

#correr el index que yo quiero y no por defecto
WORKDIR /servidor2
COPY servidor2.py .

#INSTALAR 
RUN pip install flask

#ejecutar la aplicacion
CMD ["python", "servidor2.py"]


#puerto de contenedor
EXPOSE 5000
