version: '3.8'
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx
    ports:
      - 8080:80
  servidor1:
    build: 
      context: ./Servidor1
      dockerfile: dockerfile
    container_name: servidor1
    ports:
      - 5001:5000
  servidor2:
    build: 
      context: ./Servidor2
      dockerfile: dockerfile
    container_name: servidor2
    ports:
      - 5002:5000
  servidor3:
    build: 
      context: ./Servidor3
      dockerfile: dockerfile
    container_name: servidor3
    ports:
      - 5003:5000