#imagen a usar
FROM python:latest

#correr el index que yo quiero y no por defecto
WORKDIR /servidor1
COPY servidor1.py .

#INSTALAR 
RUN pip install flask

#ejecutar la aplicacion
CMD ["python", "servidor1.py"]


#puerto de contenedor PARA TODOS LOS SERVIDORES
EXPOSE 5000
