#imagen a usar
FROM python:latest

#correr el index que yo quiero y no por defecto
WORKDIR /servidor3
COPY servidor3.py .

#INSTALAR 
RUN pip install flask

#ejecutar la aplicacion
CMD ["python", "servidor3.py"]


#puerto de contenedor
EXPOSE 5000
